FROM cyverse/reactors:python2
# FROM cyverse/reactors:python2-edge

# reactor.py, config.yml, and message.jsonschema will be automatically
# added to the container when you run docker build or abaco deploy
