FROM cyverse/reactors:python3
# FROM cyverse/reactors:python3-edge

# reactor.py, config.yml, and message.jsonschema will be automatically
# added to the container when you run docker build or abaco deploy
